#生产环境
server:
  port: 8640

spring:
  profiles:
    active: prod #对应maven多环境配置 打包：clean install -Pdev
  security:
    basic:
      path: /actuator   #多个的话以逗号分隔，默认为[/**]
    user:
      name: admin             #配置注册中心账户
      password: 123456        #配置注册中心密码
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: "/cloud-test"
  redis:   #redis集群
    cluster:
      # 各 Redis 节点信息
      nodes: 127.0.0.1:6380,127.0.0.1:6382,127.0.0.1:6384
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
#  redis:
#    database: 3
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    lettuce:
#      pool:
#        max-active: -1  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制)
#        max-idle: 8  # 连接池中的最大空闲连接
#        min-idle: 0  # 连接池中的最小空闲连接

eureka:
  port: 8400
  instance:
    hostname: 127.0.0.1              #设置当前实例的主机名称
    prefer-ip-address: true         #是否将IP注册到服务注册中心
    status-page-url: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/actuator/info         #状态页面的URL，绝对路径
    health-check-url: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/actuator/health      #健康检查页面的URL，绝对路径
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.port}/eureka/  #服务注册中心地址




