#开发环境
server:
  port: 8400

spring:
  profiles:
    active: dev #对应maven多环境配置 打包：clean install -Pdev
  security:
    basic:
      enabled: true
    user:
      name: admin             #配置注册中心账户
      password: 123456        #配置注册中心密码

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      default-zone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/  #服务注册中心地址，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔