spring:
  profiles:
    active: dev #对应maven多环境配置 打包：clean install -Pdev
  security:
    basic:
      enabled: false

server:
  port: 8400

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #服务注册中心地址