spring:
  profiles:
    active: prod
  application:
    name: cloud-center  #服务名称

server:
  port: 8600 #默认端口，子配置端口会覆盖此端口
  enable-self-preservation: false #是否开启自我保护模式
  eviction-interval-timer-in-ms: 5000 #清理无效节点,默认60*1000毫秒,即60秒
  #renewalPercentThreshold: 0.5  #设置心跳正常的阀值，默认为1，测试时可以调低

eureka:
  client:
    registerWithEureka: false #禁止注册自身
    fetchRegistry: false  #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表, 如果是服务注册中心集群，需要开启，开启就是去掉该配置，采用默认配置即可