#生产环境
server:
  port: 8620

spring:
  profiles:
    active: prod #对应maven多环境配置 打包：clean install -Pdev
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource   # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
  security:
    basic:
      path: /actuator   #多个的话以逗号分隔，默认为[/**]
    user:
      name: admin             #配置注册中心账户
      password: 123456        #配置注册中心密码
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: -1  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制)
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接

eureka:
  port: 8600
  instance:
    hostname: 127.0.0.1              #设置当前实例的主机名称
    prefer-ip-address: true         #是否将IP注册到服务注册中心
    status-page-url: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.port}/actuator/info         #状态页面的URL，绝对路径
    health-check-url: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.port}/actuator/health      #健康检查页面的URL，绝对路径
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.port}/eureka/  #服务注册中心地址


